"""
Abstract interfaces for future modules.

These protocols and ABCs define the contracts that downstream
modules (Neo4j, Qdrant, RAG, LLM Agent) will implement.
They consume cleaned metadata and transformed data directly
from the ETL pipeline output.

DO NOT implement these now — only expose the interfaces.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Protocol, runtime_checkable

import pandas as pd

from app.etl.metadata import DatabaseMetadata, RelationshipMetadata, TableMetadata


# ══════════════════════════════════════════════════════════════════════
# Data Provider — consumed by all downstream modules
# ══════════════════════════════════════════════════════════════════════

@runtime_checkable
class DataProvider(Protocol):
    """
    Protocol for modules that need access to cleaned data and metadata.

    The ETL pipeline's result object implements this protocol,
    allowing any downstream module to consume data without coupling
    to the pipeline internals.
    """

    def get_clean_dataframes(self) -> dict[str, pd.DataFrame]:
        """Return all cleaned DataFrames: table_name → DataFrame."""
        ...

    def get_table_metadata(self, table_name: str) -> TableMetadata | None:
        """Return metadata for a specific table."""
        ...

    def get_database_metadata(self) -> DatabaseMetadata:
        """Return the full database metadata graph."""
        ...

    def get_relationship_graph(self) -> dict[str, list[str]]:
        """Return the adjacency list of table relationships."""
        ...

    def get_relationships(self) -> list[RelationshipMetadata]:
        """Return all discovered relationships."""
        ...


# ══════════════════════════════════════════════════════════════════════
# Graph Exporter — for Neo4j
# ══════════════════════════════════════════════════════════════════════

class GraphExporter(ABC):
    """
    Base class for exporting cleaned data to a graph database (e.g., Neo4j).

    Subclasses implement the specific graph database client logic.
    The exporter receives data via the DataProvider interface.
    """

    @abstractmethod
    def export_nodes(
        self,
        provider: DataProvider,
        table_name: str,
    ) -> int:
        """
        Export rows from a cleaned table as graph nodes.

        Returns:
            Number of nodes created.
        """
        ...

    @abstractmethod
    def export_relationships(
        self,
        provider: DataProvider,
        relationship: RelationshipMetadata,
    ) -> int:
        """
        Export a discovered relationship as graph edges.

        Returns:
            Number of edges created.
        """
        ...

    @abstractmethod
    def export_all(self, provider: DataProvider) -> dict[str, Any]:
        """
        Export all tables and relationships to the graph database.

        Returns:
            Summary with counts of nodes and edges created.
        """
        ...


# ══════════════════════════════════════════════════════════════════════
# Vector Exporter — for Qdrant
# ══════════════════════════════════════════════════════════════════════

class VectorExporter(ABC):
    """
    Base class for exporting cleaned data to a vector database (e.g., Qdrant).

    The search_text field generated by the TransformationPipeline is the
    primary source for embedding generation.
    """

    @abstractmethod
    def create_collection(self, collection_name: str, vector_size: int) -> None:
        """Create a vector collection/index."""
        ...

    @abstractmethod
    def upsert_vectors(
        self,
        provider: DataProvider,
        table_name: str,
        text_column: str = "search_text",
    ) -> int:
        """
        Generate embeddings from the text column and upsert into the
        vector database.

        Returns:
            Number of vectors upserted.
        """
        ...

    @abstractmethod
    def search(
        self,
        query: str,
        collection_name: str,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """Search for similar vectors."""
        ...


# ══════════════════════════════════════════════════════════════════════
# Search Provider — for RAG / Hybrid Retrieval
# ══════════════════════════════════════════════════════════════════════

class SearchProvider(ABC):
    """
    Base class for hybrid search (keyword + vector) providers.

    Combines graph-based traversal (Neo4j), vector similarity (Qdrant),
    and structured queries (PostgreSQL) for RAG pipelines.
    """

    @abstractmethod
    def search(
        self,
        query: str,
        filters: dict[str, Any] | None = None,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Perform a hybrid search across all data sources.

        Returns:
            Ranked list of result documents with metadata and scores.
        """
        ...

    @abstractmethod
    def get_context(
        self,
        query: str,
        max_tokens: int = 4096,
    ) -> str:
        """
        Retrieve and format context for an LLM prompt.

        Returns:
            Formatted context string ready for LLM consumption.
        """
        ...


# ══════════════════════════════════════════════════════════════════════
# Entity Resolver — for cross-table entity linking
# ══════════════════════════════════════════════════════════════════════

class EntityResolver(ABC):
    """
    Base class for entity resolution across tables.

    Uses cleaned data to identify and link duplicate/related entities
    (e.g., same person appearing as accused in one case and witness
    in another).
    """

    @abstractmethod
    def resolve(
        self,
        provider: DataProvider,
        entity_type: str,
    ) -> list[dict[str, Any]]:
        """
        Resolve entities of a given type across tables.

        Returns:
            List of entity clusters with linked records.
        """
        ...
